-- Insert missing leagues from batch_10.sql
-- ID 397
INSERT INTO "league_league" ("id", "name", "day_of_week", "team_registration_credit", "registration_cost", "team_cost", "num_players_on_field", "minimum_roster_size", "minimum_num_women_on_field", "status", "league_description", "game_location", "game_time", "registration_deadline", "open_team_count", "open_female_slot", "open_male_slot", "season_id", "cover_description", "image", "location_id", "game_duration", "order", "league_type", "competition_type", "featured_at_homepage", "paypal_account_id") VALUES
(397,'BROOKLYN BRIDGE PARK Fall 2025 Outdoor 9s','1',0,155,1850,9,12,3,3,'<p><strong>Note: A change to format meaning two (2) female players required on the outfield now.</strong></p>\r\n<p>&nbsp;</p>\r\n<p>Opening night for new registrant is September 23rd.</p>\r\n<p>&nbsp;</p>\r\n<p>The games are 9-a-side requiring a goalkeeper and eight outfield players. While the ''keeper is non-gender specific, a minimum of TWO female players must constitute the outfield participants at all times.</p>\r\n<p>&nbsp;</p>\r\n<p>Rosters should be a minimum of 12 players and take into account the on-field requirements. Captains can register by making an Individual Payment - teammates will then be able to register/pay individually prior to a deadline.</p>\r\n<p>&nbsp;</p>\r\n<p>Payment of the one-time Team Fee allows 16 players on the official roster - Team Fees must be made as a one-off payment at the outset of registration.</p>\r\n<p>&nbsp;</p>\r\n<p>48 minute games and teams will have a minimum of 8 fixtures.</p>','','Tuesdays 6:30pm-9pm','2025-09-27',0,0,0,3,NULL,'/static/img/leagues/league-1.jpg',5,48,0,'COED','Pool Stage Competition',false,1);

-- ID 398
INSERT INTO "league_league" ("id", "name", "day_of_week", "team_registration_credit", "registration_cost", "team_cost", "num_players_on_field", "minimum_roster_size", "minimum_num_women_on_field", "status", "league_description", "game_location", "game_time", "registration_deadline", "open_team_count", "open_female_slot", "open_male_slot", "season_id", "cover_description", "image", "location_id", "game_duration", "order", "league_type", "competition_type", "featured_at_homepage", "paypal_account_id") VALUES
(398,'GANSEVOORT Fall 2025 Outdoor 7s','2',0,155,1600,7,11,2,3,'<p>Opening night is Wednesday September 3rd and 10th, depending upon your scheduling assignment.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>LOCATION</strong>: Games are played at Gansevoort Peninsula Athletic Field, NY 10014 on the Hudson across from the Meatpacking District.</p>\r\n<p>&nbsp;</p>\r\n<p>The games are 7-a-side requiring a goalkeeper and six outfield players. While the ''keeper is non-gender specific, a <strong>minimum of two female</strong> players must constitute the outfield participants at all times.</p>\r\n<p>&nbsp;</p>\r\n<p>Rosters should be a minimum of 11 players and take into account the on-field requirements. Captains can register by making an Individual Payment - teammates will then be able to register/pay individually prior to a deadline.</p>\r\n<p>&nbsp;</p>\r\n<p>Payment of the one-time Team Fee allows 15 players on the official roster - Team Fees must be made as a one-off payment at the outset of registration.</p>\r\n<p>&nbsp;</p>\r\n<p>Games consist of 44 minutes of continuous play and teams will have a minimum of 7 fixtures.</p>\r\n<p>&nbsp;</p>\r\n<p>Kick-offs will be 7pm and 7:45pm. Teams will rotate within these slots over the course of the season.</p>','','Games are played 7pm-8:30pm','2025-09-10',0,0,0,3,NULL,'/static/img/leagues/league-1.jpg',1,44,0,'COED','Pool Stage Competition',false,1);

-- ID 399
INSERT INTO "league_league" ("id", "name", "day_of_week", "team_registration_credit", "registration_cost", "team_cost", "num_players_on_field", "minimum_roster_size", "minimum_num_women_on_field", "status", "league_description", "game_location", "game_time", "registration_deadline", "open_team_count", "open_female_slot", "open_male_slot", "season_id", "cover_description", "image", "location_id", "game_duration", "order", "league_type", "competition_type", "featured_at_homepage", "paypal_account_id") VALUES
(399,'MIDTOWN WEST - DeWitt Clinton Fall 2025 Outdoor 7s','3',0,155,1600,7,11,2,3,'<p>Opening night is September 18th.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>LOCATION</strong>: Games are played at DeWitt Clinton Park (52nd &amp; 11th Ave.).</p>\r\n<p>&nbsp;</p>\r\n<p>The games are 7-a-side requiring a goalkeeper and six outfield players. While the ''keeper is non-gender specific, a <strong>minimum of two female</strong> players must constitute the outfield participants at all times.</p>\r\n<p>&nbsp;</p>\r\n<p>Rosters should be a minimum of 11 players and take into account the on-field requirements. Captains can register by making an Individual Payment - teammates will then be able to register/pay individually prior to a deadline.</p>\r\n<p>&nbsp;</p>\r\n<p>Payment of the one-time Team Fee allows 15 players on the official roster - Team Fees must be made as a one-off payment at the outset of registration.</p>\r\n<p>&nbsp;</p>\r\n<p>Games consist of 25-minute halves and teams will have a minimum of 7 fixtures.</p>\r\n<p>&nbsp;</p>\r\n<p>Kick-offs will be 8pm and 8:55pm. Teams will rotate within these slots over the course of the season.</p>','<p><strong>&nbsp;</strong></p>','Games are played 8pm-10pm','2025-09-19',0,0,0,3,NULL,'/static/img/leagues/league-1.jpg',10,50,0,'COED','Pool Stage Competition',true,1);

-- ID 405
INSERT INTO "league_league" ("id", "name", "day_of_week", "team_registration_credit", "registration_cost", "team_cost", "num_players_on_field", "minimum_roster_size", "minimum_num_women_on_field", "status", "league_description", "game_location", "game_time", "registration_deadline", "open_team_count", "open_female_slot", "open_male_slot", "season_id", "cover_description", "image", "location_id", "game_duration", "order", "league_type", "competition_type", "featured_at_homepage", "paypal_account_id") VALUES
(405,'WILLIAMSBURG Winter 2025/26 Outdoor 7s','3',0,140,1350,7,11,2,2,'<p>The season will start on January 8th.</p>\r\n<p>&nbsp;</p>\r\n<p>The games are 7-a-side requiring a goalkeeper and six outfield players. While the ''keeper is non-gender specific, a minimum of two female players must constitute the outfield participants at all times.</p>\r\n<p>&nbsp;</p>\r\n<p>Rosters should be a minimum of 10 players and take into account the on-field requirements. Captains can register by making an Individual Payment - teammates will then be able to register/pay individually prior to a deadline.</p>\r\n<p>&nbsp;</p>\r\n<p>Captains also have the option of submitting a Team Fee - this needs to be submitted at the outset of registration in a one-time payment. With a Team Fee, rosters can be of any size.</p>\r\n<p>&nbsp;</p>\r\n<p>Games are played 8pm-10pm.</p>\r\n<p>&nbsp;</p>','<p>To register for this League, please sign into your player profile by clicking<strong> <a href=\"../../../../../login/\">HERE</a>.</strong></p>\r\n<p><strong>&nbsp;</strong></p>','Games are played 8pm-10pm.','2026-01-09',0,0,0,3,NULL,'/static/img/leagues/league-1.jpg',10,50,2,'COED','Pool Stage Competition',true,1);
