# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 20:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_localflavor_us.models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(blank=True, default=30, null=True)),
                ('team_a_score', models.IntegerField(default=0)),
                ('team_b_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Scheduled', 'Scheduled'), ('Draft', 'Draft')], default='Scheduled', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('tag', models.SlugField()),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('lon', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('image', models.ImageField(default='/static/img/venues/venue-1.jpg', upload_to='venues/')),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='minimum_num_women_on_field',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='minimum number of women on the field'),
        ),
        migrations.AlterField(
            model_name='league',
            name='num_players_on_field',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True, verbose_name='number of players on the field'),
        ),
        migrations.AlterField(
            model_name='league',
            name='open_female_slot',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='number of free-agent women accepted'),
        ),
        migrations.AlterField(
            model_name='league',
            name='open_male_slot',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='number of free-agent men accepted'),
        ),
        migrations.AlterField(
            model_name='league',
            name='open_team_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='number of new teams accepted'),
        ),
        migrations.AlterField(
            model_name='league',
            name='status',
            field=models.IntegerField(choices=[(13, 'Priority Registration'), (1, 'Open Registration'), (2, 'Active Season'), (3, 'Season Complete'), (4, 'Disabled')], default=2),
        ),
        migrations.AlterField(
            model_name='paymentplaceholder',
            name='placeholder_type',
            field=models.IntegerField(choices=[(2, 'Existing team, team payment'), (3, 'Existing team, individual payment'), (4, 'New team, team payment'), (5, 'New team, individual payment'), (1, 'Individual'), (6, 'Open')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='experience_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Advanced Beginner', 'Advanced Beginner'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced')], max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='interested_in_soccer_school',
            field=models.BooleanField(help_text='I would like to know more about NY Coed Soccer School', verbose_name='soccer school'),
        ),
        migrations.AlterField(
            model_name='player',
            name='state',
            field=django_localflavor_us.models.USStateField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='NY', max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.IntegerField(choices=[(2, 'Active'), (4, 'Disabled')], default=2),
        ),
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.IntegerField(choices=[(2, 'Active'), (6, 'Inactive')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='historical_team',
            field=models.ForeignKey(blank=True, help_text="The historical team record allows a team's stats to be tracked from season to season without requiring the team's name to remain constant.\tIf none is specified, a new one will automatically be created.", null=True, on_delete=django.db.models.deletion.CASCADE, to='league.HistoricalTeam', verbose_name='Historical Team Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='override_payment',
            field=models.BooleanField(default=False, help_text="By default, the 'Payment status' option is a reflection of the data the system has received from PayPal, and will be updated as PayPal receives new information about this payment. To manually specify payment status, check this box to keep the system from overwriting your input."),
        ),
        migrations.AlterField(
            model_name='team',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='If you manually change the payment information, this field provides an opportunity for you to make internal notes about payment status.  It is not publicly visible.'),
        ),
        migrations.AlterField(
            model_name='team',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Pending'), (3, 'Approved'), (2, 'Rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='payment_type',
            field=models.IntegerField(blank=True, choices=[(4, 'Team'), (1, 'Individual')], null=True),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='override_payment',
            field=models.BooleanField(default=False, help_text="By default, the 'Payment status' option is a reflection of the data the system has received from PayPal, and will be updated as PayPal receives new information about this payment. To manually specify payment status, check this box to keep the system from overwriting your input."),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='If you manually change the payment information, this field provides an opportunity for you to make internal notes about payment status.  It is not publicly visible.'),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Pending'), (3, 'Approved'), (2, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_local', to='league.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_visitor', to='league.Team'),
        ),
    ]
