# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20170408_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contact_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='emergency_contact_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='interested_in_brooklyn_leagues',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='interested_in_manhattan_leagues',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='interested_in_soccer_school',
            field=models.BooleanField(default=False, help_text='I would like to know more about NY Coed Soccer School', verbose_name='soccer school'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'Active'), (4, 'Disabled')], default=2, null=True),
        ),
    ]
