# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20170411_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='league',
            name='game_duration',
            field=models.PositiveSmallIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='registration_deadline',
            field=models.DateField(),
        ),
    ]
