# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20170414_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='order',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
