# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20170420_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
    ]
