# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20170421_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_type',
            field=models.CharField(choices=[(b'COED', b'COED'), (b"Men's", b"Men's")], default=b'COED', max_length=128),
        ),
    ]
