# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_auto_20170423_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('day_of_week', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=13)),
                ('page', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season')),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='league_type',
            field=models.CharField(choices=[('COED', 'COED'), ("Men's", "Men's")], default='COED', max_length=128),
        ),
    ]
