# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_auto_20170426_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacyleague',
            name='slug',
            field=models.SlugField(default='do-not-fill', editable=False, max_length=150, unique=True),
        ),
    ]
