# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_auto_20170427_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
