# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_venue_google_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyleague',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
