# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_legacyleague_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='competition_type',
            field=models.CharField(choices=[(b'League', b'League Competition'), (b'Tournament', b'Tournament Competition'), (b'Soccer School', b'Soccer School Competition')], default=b'League', max_length=128),
        ),
    ]
