# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 00:06
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_league_competition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='reprogramming_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='rescheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_placeholder',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_placeholder',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_local', to='league.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_visitor', to='league.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='color_name',
            field=colorfield.fields.ColorField(blank=True, max_length=10),
        ),
    ]
