# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_auto_20170516_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(default='ROUND', max_length=128)),
                ('order', models.PositiveIntegerField(default=1)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Division')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
        migrations.AlterField(
            model_name='league',
            name='competition_type',
            field=models.CharField(choices=[('League', 'League Competition'), ('Tournament', 'Tournament Competition'), ('Soccer School', 'Soccer School Competition')], default='League', max_length=128),
        ),
        migrations.AddField(
            model_name='round',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.Round'),
        ),
    ]
