# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_goalscorer'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalscorer',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Division'),
        ),
    ]
