# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 00:11
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_goalscorer_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='game_location',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
