# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_auto_20170606_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='competition_type',
            field=models.CharField(choices=[('League', 'League Competition'), ('Tournament', 'Tournament Competition'), ('Soccer School', 'Soccer School Competition'), ('Pool Stage Competition', 'Pool Stage Competition (Multiple Groups)')], default='League', max_length=128),
        ),
    ]
