# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0025_auto_20170613_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='order',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
