# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_venue_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('receiver_email', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='paypal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.PayPalAccount'),
        ),
    ]
