# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_auto_20171031_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalaccount',
            name='secondary_email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
