# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0028_paypalaccount_secondary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalaccount',
            name='company',
            field=models.CharField(default='[Company Name]', max_length=128),
        ),
    ]
