# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_paypalaccount_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('day_of_week', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=13)),
                ('slug', models.SlugField(default=b'do-not-fill', editable=False, max_length=150, unique=True)),
                ('external_url', models.URLField(default=b'http://www.')),
                ('active', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season')),
            ],
        ),
    ]
