# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_localflavor_us.models
import phonenumber_field.modelfields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paypal', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('team_registration_credit', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('registration_cost', models.PositiveIntegerField()),
                ('team_cost', models.PositiveIntegerField()),
                ('num_players_on_field', models.PositiveSmallIntegerField(blank=True, default=5, null=True, verbose_name=b'number of players on the field')),
                ('minimum_roster_size', models.PositiveSmallIntegerField(blank=True, default=5, null=True)),
                ('minimum_num_women_on_field', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'minimum number of women on the field')),
                ('status', models.IntegerField(choices=[(13, b'Priority Registration'), (1, b'Open Registration'), (2, b'Active Season'), (3, b'Season Complete'), (4, b'Disabled')], default=2)),
                ('league_description', tinymce.models.HTMLField()),
                ('game_location', tinymce.models.HTMLField()),
                ('game_time', models.CharField(max_length=80)),
                ('registration_deadline', models.CharField(max_length=128)),
                ('open_team_count', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'number of new teams accepted')),
                ('open_female_slot', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'number of free-agent women accepted')),
                ('open_male_slot', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name=b'number of free-agent men accepted')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PaymentPlaceholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder_type', models.IntegerField(choices=[(2, b'Existing team, team payment'), (3, b'Existing team, individual payment'), (4, b'New team, team payment'), (5, b'New team, individual payment'), (1, b'Individual'), (6, b'Open')])),
                ('team_name', models.CharField(blank=True, max_length=80)),
                ('cost', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(2, b'Active'), (4, b'Disabled')], default=2)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=40)),
                ('address', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', django_localflavor_us.models.USStateField(blank=True, choices=[(b'AL', b'Alabama'), (b'AK', b'Alaska'), (b'AS', b'American Samoa'), (b'AZ', b'Arizona'), (b'AR', b'Arkansas'), (b'AA', b'Armed Forces Americas'), (b'AE', b'Armed Forces Europe'), (b'AP', b'Armed Forces Pacific'), (b'CA', b'California'), (b'CO', b'Colorado'), (b'CT', b'Connecticut'), (b'DE', b'Delaware'), (b'DC', b'District of Columbia'), (b'FL', b'Florida'), (b'GA', b'Georgia'), (b'GU', b'Guam'), (b'HI', b'Hawaii'), (b'ID', b'Idaho'), (b'IL', b'Illinois'), (b'IN', b'Indiana'), (b'IA', b'Iowa'), (b'KS', b'Kansas'), (b'KY', b'Kentucky'), (b'LA', b'Louisiana'), (b'ME', b'Maine'), (b'MD', b'Maryland'), (b'MA', b'Massachusetts'), (b'MI', b'Michigan'), (b'MN', b'Minnesota'), (b'MS', b'Mississippi'), (b'MO', b'Missouri'), (b'MT', b'Montana'), (b'NE', b'Nebraska'), (b'NV', b'Nevada'), (b'NH', b'New Hampshire'), (b'NJ', b'New Jersey'), (b'NM', b'New Mexico'), (b'NY', b'New York'), (b'NC', b'North Carolina'), (b'ND', b'North Dakota'), (b'MP', b'Northern Mariana Islands'), (b'OH', b'Ohio'), (b'OK', b'Oklahoma'), (b'OR', b'Oregon'), (b'PA', b'Pennsylvania'), (b'PR', b'Puerto Rico'), (b'RI', b'Rhode Island'), (b'SC', b'South Carolina'), (b'SD', b'South Dakota'), (b'TN', b'Tennessee'), (b'TX', b'Texas'), (b'UT', b'Utah'), (b'VT', b'Vermont'), (b'VI', b'Virgin Islands'), (b'VA', b'Virginia'), (b'WA', b'Washington'), (b'WV', b'West Virginia'), (b'WI', b'Wisconsin'), (b'WY', b'Wyoming')], default=b'NY', max_length=2)),
                ('zip', models.CharField(max_length=12)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('emergency_contact_name', models.CharField(max_length=80)),
                ('emergency_contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('interested_in_brooklyn_leagues', models.BooleanField()),
                ('interested_in_manhattan_leagues', models.BooleanField()),
                ('interested_in_soccer_school', models.BooleanField(help_text=b'I would like to know more about NY Coed Soccer School', verbose_name=b'soccer school')),
                ('administrator_notes', models.TextField(blank=True, max_length=2000)),
                ('experience_level', models.CharField(choices=[(b'Beginner', b'Beginner'), (b'Advanced Beginner', b'Advanced Beginner'), (b'Intermediate', b'Intermediate'), (b'Experienced', b'Experienced')], max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('status', models.IntegerField(choices=[(2, b'Active'), (6, b'Inactive')])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color_name', models.CharField(blank=True, max_length=40)),
                ('administrator_notes', models.TextField(blank=True, max_length=2000)),
                ('payment_status', models.IntegerField(choices=[(0, b'Unpaid'), (1, b'Pending'), (3, b'Approved'), (2, b'Rejected')], default=0)),
                ('payment_type', models.IntegerField(blank=True, choices=[(4, b'Team'), (1, b'Individual')], null=True)),
                ('override_payment', models.BooleanField(default=False, help_text=b"By default, the 'Payment status' option is a reflection of the data the system has received from PayPal, and will be updated as PayPal receives new information about this payment. To manually specify payment status, check this box to keep the system from overwriting your input.")),
                ('payment_notes', models.TextField(blank=True, help_text=b'If you manually change the payment information, this field provides an opportunity for you to make internal notes about payment status.  It is not publicly visible.')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Division')),
                ('historical_team', models.ForeignKey(blank=True, help_text=b"The historical team record allows a team's stats to be tracked from season to season without requiring the team's name to remain constant.\tIf none is specified, a new one will automatically be created.", null=True, on_delete=django.db.models.deletion.CASCADE, to='league.HistoricalTeam', verbose_name=b'Historical Team Name')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paypal.PayPalIPN')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField()),
                ('payment_status', models.IntegerField(choices=[(0, b'Unpaid'), (1, b'Pending'), (3, b'Approved'), (2, b'Rejected')], default=0)),
                ('override_payment', models.BooleanField(default=False, help_text=b"By default, the 'Payment status' option is a reflection of the data the system has received from PayPal, and will be updated as PayPal receives new information about this payment. To manually specify payment status, check this box to keep the system from overwriting your input.")),
                ('payment_notes', models.TextField(blank=True, help_text=b'If you manually change the payment information, this field provides an opportunity for you to make internal notes about payment status.  It is not publicly visible.')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paypal.PayPalIPN')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Team')),
            ],
            options={
                'verbose_name': 'Team roster record',
                'verbose_name_plural': 'Team Roster',
            },
        ),
        migrations.CreateModel(
            name='WebsiteIncludeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='league.TeamPlayer', to='league.Player'),
        ),
        migrations.AddField(
            model_name='paymentplaceholder',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Player'),
        ),
        migrations.AddField(
            model_name='paymentplaceholder',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season'),
        ),
        migrations.AddField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
    ]
