# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20170408_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='cover_description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='image',
            field=models.ImageField(default='/static/img/leagues/league-1.jpg', upload_to='leagues/'),
        ),
        migrations.AddField(
            model_name='league',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Venue'),
        ),
    ]
