# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_league_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ('-order',)},
        ),
        migrations.AlterField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='league.League'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='league.League'),
        ),
    ]
