# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 21:54
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_team_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='day_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=13),
        ),
    ]
