# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_auto_20170519_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='duration',
        ),
    ]
