# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_league_featured_at_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalScorer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.TeamPlayer')),
            ],
        ),
    ]
