# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_auto_20170605_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='division',
            name='order',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
